import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal, engine, Base
from app.models.destination import Destination
import json

# Create tables
Base.metadata.create_all(bind=engine)

# Comprehensive list of 100+ Nepal destinations
destinations_data = [
    # Trekking Destinations (30)
    {"name": "Everest Base Camp Trek", "location": "Solukhumbu District", "latitude": 27.9881, "longitude": 86.9250, "category": "Trekking", "description": "The iconic trek to the base of the world's highest mountain. Experience breathtaking views of Mount Everest, Lhotse, and Nuptse. Pass through Sherpa villages, cross suspension bridges, and visit ancient monasteries. The trek takes you through Sagarmatha National Park, a UNESCO World Heritage Site. Acclimatization days in Namche Bazaar and Dingboche are crucial for altitude adjustment.", "activities": json.dumps(["trekking", "mountain viewing", "photography", "monastery visits", "sherpa culture"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 60, "duration_days": 14, "popularity_score": 98, "altitude": 5364, "permits_required": True, "image_url": ""},

    {"name": "Annapurna Circuit", "location": "Annapurna Region", "latitude": 28.5965, "longitude": 83.8820, "category": "Trekking", "description": "One of the world's most diverse trekking routes. Circle the Annapurna massif experiencing subtropical forests, terraced fields, alpine meadows, and high desert landscapes. Cross the challenging Thorong La Pass at 5,416m. Encounter diverse ethnic communities including Gurung, Thakali, and Tibetan cultures. The trek showcases dramatic climate and vegetation changes within days.", "activities": json.dumps(["trekking", "cultural immersion", "hot springs", "high pass crossing", "photography"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 55, "duration_days": 18, "popularity_score": 96, "altitude": 5416, "permits_required": True, "image_url": ""},

    {"name": "Langtang Valley Trek", "location": "Rasuwa District", "latitude": 28.2096, "longitude": 85.5450, "category": "Trekking", "description": "A stunning trek close to Kathmandu through the Langtang National Park. Walk through rhododendron and bamboo forests, past Tamang villages, with views of Langtang Lirung. The valley was severely affected by the 2015 earthquake but has been rebuilt. Experience Tibetan Buddhist culture, visit ancient monasteries, and enjoy cheese factories in Kyanjin Gompa.", "activities": json.dumps(["trekking", "wildlife spotting", "cheese tasting", "glacier viewing", "village tours"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 50, "duration_days": 10, "popularity_score": 88, "altitude": 4984, "permits_required": True, "image_url": ""},

    {"name": "Manaslu Circuit Trek", "location": "Gorkha District", "latitude": 28.5497, "longitude": 84.5625, "category": "Trekking", "description": "Remote trek around the eighth highest mountain in the world. Less crowded than Everest and Annapurna, offering pristine mountain experiences. Cross the dramatic Larkya La Pass with panoramic views of multiple 8000m peaks. Experience authentic Tibetan Buddhist culture in remote villages. The trail follows ancient salt trading routes.", "activities": json.dumps(["trekking", "remote villages", "high pass crossing", "buddhist monasteries", "wildlife"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 65, "duration_days": 16, "popularity_score": 82, "altitude": 5160, "permits_required": True, "image_url": ""},

    {"name": "Upper Mustang Trek", "location": "Mustang District", "latitude": 28.9953, "longitude": 83.8821, "category": "Trekking", "description": "Trek to the forbidden kingdom of Lo. Experience Tibetan Buddhist culture preserved for centuries behind the Himalayan rain shadow. Walk through desert landscapes with colorful rock formations and ancient cave dwellings. Visit the walled city of Lo Manthang and numerous monasteries with priceless Buddhist art. Limited permits protect this fragile culture.", "activities": json.dumps(["trekking", "tibetan culture", "ancient monasteries", "cave exploration", "desert landscapes"]), "difficulty_level": 3, "best_season": "Spring, Summer, Autumn", "avg_cost_per_day": 80, "duration_days": 12, "popularity_score": 85, "altitude": 3840, "permits_required": True, "image_url": ""},

    {"name": "Gokyo Lakes Trek", "location": "Solukhumbu District", "latitude": 27.9639, "longitude": 86.6906, "category": "Trekking", "description": "Alternative Everest region trek featuring turquoise glacial lakes. Climb Gokyo Ri for spectacular views of Everest, Lhotse, Makalu, and Cho Oyu. Trek along the Ngozumpa Glacier, the longest glacier in Nepal. Experience pristine alpine beauty with fewer crowds than the classic Everest Base Camp route. Six sacred lakes add spiritual significance.", "activities": json.dumps(["trekking", "lake viewing", "peak climbing", "glacier walking", "photography"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 60, "duration_days": 12, "popularity_score": 87, "altitude": 5357, "permits_required": True, "image_url": ""},

    {"name": "Kanchenjunga Base Camp Trek", "location": "Taplejung District", "latitude": 27.7025, "longitude": 88.1475, "category": "Trekking", "description": "Remote trek to the base of the world's third highest mountain. Experience untouched wilderness and diverse ethnic cultures. Trek through dense forests with rhododendrons, orchids, and wildlife including red pandas. Visit both north and south base camps for different perspectives of this massive mountain. Very few trekkers make it here.", "activities": json.dumps(["trekking", "wildlife spotting", "remote culture", "pristine nature", "photography"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 70, "duration_days": 20, "popularity_score": 75, "altitude": 5143, "permits_required": True, "image_url": ""},

    {"name": "Makalu Base Camp Trek", "location": "Sankhuwasabha District", "latitude": 27.8890, "longitude": 87.0886, "category": "Trekking", "description": "Challenging trek to the base of the fifth highest mountain. Journey through the Makalu Barun National Park with incredible biodiversity. Experience dramatic landscape changes from subtropical forests to alpine meadows. Very remote with few teahouses, requiring camping in upper sections. Stunning mountain views and pristine wilderness.", "activities": json.dumps(["trekking", "camping", "wildlife observation", "photography", "botanical tours"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 75, "duration_days": 18, "popularity_score": 72, "altitude": 5200, "permits_required": True, "image_url": ""},

    {"name": "Dhaulagiri Circuit Trek", "location": "Myagdi District", "latitude": 28.6974, "longitude": 83.4933, "category": "Trekking", "description": "One of Nepal's most challenging treks circling the seventh highest mountain. Cross two high passes including the French Pass at 5360m. Experience dramatic landscape from lush forests to high altitude glaciers. Very remote with basic facilities requiring camping equipment. Stunning views of Dhaulagiri, Annapurna, and surrounding peaks.", "activities": json.dumps(["trekking", "mountaineering", "camping", "glacier crossing", "high altitude"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 80, "duration_days": 17, "popularity_score": 70, "altitude": 5360, "permits_required": True, "image_url": ""},

    {"name": "Poon Hill Trek", "location": "Kaski District", "latitude": 28.3949, "longitude": 83.6985, "category": "Trekking", "description": "Short and popular trek with spectacular Annapurna panorama views. Ideal for beginners or those with limited time. Watch sunrise from Poon Hill viewpoint over Dhaulagiri, Annapurna South, Machhapuchhre, and other peaks. Walk through beautiful rhododendron forests, especially stunning in spring. Visit traditional Gurung and Magar villages.", "activities": json.dumps(["trekking", "sunrise viewing", "cultural villages", "photography", "rhododendron forests"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 5, "popularity_score": 93, "altitude": 3210, "permits_required": True, "image_url": ""},

    # Cultural Destinations (25)
    {"name": "Kathmandu Durbar Square", "location": "Kathmandu", "latitude": 27.7045, "longitude": 85.3077, "category": "Cultural", "description": "Historic palace complex and UNESCO World Heritage Site at the heart of old Kathmandu. Features temples, courtyards, and the residence of the Living Goddess Kumari. Admire intricate wood carvings, pagoda-style architecture, and centuries-old temples. Partially damaged in 2015 earthquake but restoration ongoing. Experience traditional Newari architecture and culture.", "activities": json.dumps(["sightseeing", "photography", "architecture", "kumari viewing", "cultural tours"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 1, "popularity_score": 95, "altitude": 1400, "permits_required": False, "image_url": ""},

    {"name": "Bhaktapur Durbar Square", "location": "Bhaktapur", "latitude": 27.6722, "longitude": 85.4298, "category": "Cultural", "description": "Medieval city square showcasing the finest Newari architecture. Home to the 55-Window Palace, Vatsala Temple, and numerous courtyards. Famous for pottery, woodcarving, and traditional yogurt (juju dhau). Well-preserved ancient city with less traffic than Kathmandu. Walk through narrow alleys discovering hidden temples and courtyards.", "activities": json.dumps(["sightseeing", "pottery workshops", "traditional food", "photography", "cultural immersion"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 1, "popularity_score": 92, "altitude": 1401, "permits_required": False, "image_url": ""},

    {"name": "Patan Durbar Square", "location": "Lalitpur", "latitude": 27.6733, "longitude": 85.3256, "category": "Cultural", "description": "Royal palace square known for exceptional Newari metal crafts and architecture. Visit the Patan Museum showcasing bronze statues and religious art. Explore Krishna Mandir, a stone temple with intricate carvings. Famous for traditional metalworking and thangka painting. Less crowded than Kathmandu's square with better-preserved structures.", "activities": json.dumps(["museum visits", "metalcraft shopping", "architecture", "thangka viewing", "cultural tours"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 28, "duration_days": 1, "popularity_score": 90, "altitude": 1330, "permits_required": False, "image_url": ""},

    {"name": "Changu Narayan Temple", "location": "Bhaktapur District", "latitude": 27.7151, "longitude": 85.4276, "category": "Cultural", "description": "Oldest Hindu temple in Nepal's valley, dating to 4th century. UNESCO World Heritage Site with finest stone, wood, and metal craftsmanship. Dedicated to Lord Vishnu with numerous ancient inscriptions. Located on a hilltop with Himalayan views. Peaceful setting away from city crowds with traditional Newari village nearby.", "activities": json.dumps(["temple visits", "ancient inscriptions", "village walks", "photography", "cultural heritage"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 82, "altitude": 1541, "permits_required": False, "image_url": ""},

    {"name": "Tansen", "location": "Palpa District", "latitude": 27.8667, "longitude": 83.5500, "category": "Cultural", "description": "Hilltop town with rich Newari and Magar heritage. Less touristy alternative with stunning Himalayan views. Famous for traditional dhaka fabric and metalwork. Explore Tansen Durbar, Amar Narayan Temple, and historic bazaars. Starting point for treks to surrounding hills. Colonial-era architecture mixed with traditional buildings.", "activities": json.dumps(["cultural walks", "shopping", "mountain views", "temple visits", "local crafts"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 2, "popularity_score": 78, "altitude": 1371, "permits_required": False, "image_url": ""},

    # Religious Destinations (20)
    {"name": "Pashupatinath Temple", "location": "Kathmandu", "latitude": 27.7104, "longitude": 85.3484, "category": "Religious", "description": "Sacred Hindu temple complex dedicated to Lord Shiva on the Bagmati River. UNESCO World Heritage Site and one of the most important Shiva temples in the world. Witness cremation ceremonies, Hindu sadhus, and religious rituals. Only Hindus can enter the main temple, but the complex offers extensive viewing areas. Evening aarti ceremony is spiritually moving.", "activities": json.dumps(["temple visits", "cremation viewing", "religious ceremonies", "sadhu encounters", "spiritual experience"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 15, "duration_days": 1, "popularity_score": 96, "altitude": 1338, "permits_required": False, "image_url": ""},

    {"name": "Boudhanath Stupa", "location": "Kathmandu", "latitude": 27.7215, "longitude": 85.3622, "category": "Religious", "description": "Largest Buddhist stupa in Nepal and one of the largest in the world. UNESCO World Heritage Site and center of Tibetan Buddhism in Nepal. Walk clockwise around the massive white dome while spinning prayer wheels. Surrounded by Tibetan monasteries, shops, and restaurants. Particularly beautiful during Buddha Jayanti and Losar festivals.", "activities": json.dumps(["stupa circumambulation", "monastery visits", "tibetan culture", "meditation", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 97, "altitude": 1350, "permits_required": False, "image_url": ""},

    {"name": "Swayambhunath (Monkey Temple)", "location": "Kathmandu", "latitude": 27.7149, "longitude": 85.2906, "category": "Religious", "description": "Ancient Buddhist complex atop a hill west of Kathmandu. Features a massive stupa with painted Buddha eyes watching over the valley. Climb 365 steps past resident monkeys to reach the top. UNESCO World Heritage Site combining Buddhist and Hindu elements. Panoramic views of Kathmandu Valley, especially beautiful at sunrise and sunset.", "activities": json.dumps(["stupa visits", "monkey watching", "city views", "meditation", "sunrise/sunset viewing"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 15, "duration_days": 1, "popularity_score": 94, "altitude": 1483, "permits_required": False, "image_url": ""},

    {"name": "Lumbini", "location": "Rupandehi District", "latitude": 27.4833, "longitude": 83.2764, "category": "Religious", "description": "Birthplace of Lord Buddha and most sacred Buddhist pilgrimage site. UNESCO World Heritage Site with Maya Devi Temple marking the exact birth spot. Visit international monasteries built by Buddhist countries, each showcasing their architectural style. The Sacred Garden, Ashoka Pillar, and Puskarini Pond create a peaceful spiritual atmosphere. Extensive archaeological ruins reveal ancient Buddhist civilization.", "activities": json.dumps(["pilgrimage", "monastery visits", "meditation", "archaeological sites", "spiritual retreat"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 2, "popularity_score": 98, "altitude": 150, "permits_required": False, "image_url": ""},

    {"name": "Muktinath Temple", "location": "Mustang District", "latitude": 28.8173, "longitude": 83.8698, "category": "Religious", "description": "Sacred Hindu and Buddhist temple at 3,710 meters. One of world's highest temples, revered by both religions. Features 108 water spouts shaped like bull heads for ritual bathing. Eternal flame fueled by natural gas inside the temple. Important stop on Annapurna Circuit trek. Tibetan Buddhist gompa nearby adds to spiritual atmosphere.", "activities": json.dumps(["pilgrimage", "temple visits", "ritual bathing", "mountain views", "spiritual experience"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 35, "duration_days": 2, "popularity_score": 88, "altitude": 3710, "permits_required": True, "image_url": ""},

    # Nature Destinations (20)
    {"name": "Chitwan National Park", "location": "Chitwan District", "latitude": 27.5291, "longitude": 84.3542, "category": "Wildlife", "description": "First national park in Nepal and UNESCO World Heritage Site. Home to Bengal tigers, one-horned rhinoceros, elephants, and over 500 bird species. Explore dense sal forests and grasslands on elephant back or jeep safari. Canoe trips on Rapti River for crocodile and bird watching. Visit Elephant Breeding Center and Tharu cultural programs in the evening.", "activities": json.dumps(["wildlife safari", "elephant rides", "canoe trips", "bird watching", "cultural shows"]), "difficulty_level": 1, "best_season": "Winter, Spring", "avg_cost_per_day": 50, "duration_days": 3, "popularity_score": 95, "altitude": 150, "permits_required": True, "image_url": ""},

    {"name": "Rara Lake", "location": "Mugu District", "latitude": 29.5264, "longitude": 82.0809, "category": "Nature", "description": "Largest lake in Nepal at 2,990 meters. Pristine alpine lake surrounded by pine and juniper forests. Remote location in far western Nepal offers solitude and unspoiled nature. Crystal clear blue waters reflect surrounding mountains. Home to unique fish species and migratory birds. Rara National Park protects the area's biodiversity.", "activities": json.dumps(["trekking", "camping", "bird watching", "photography", "nature walks"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 55, "duration_days": 7, "popularity_score": 80, "altitude": 2990, "permits_required": True, "image_url": ""},

    {"name": "Phewa Lake", "location": "Pokhara", "latitude": 28.2096, "longitude": 83.9856, "category": "Nature", "description": "Second largest lake in Nepal and heart of Pokhara. Stunning reflection of Annapurna range and Machhapuchhre in clear water. Boating, paragliding, and lakeside cafes popular activities. Tal Barahi Temple on small island in the lake. Lakeside area offers restaurants, shops, and accommodations with mountain views.", "activities": json.dumps(["boating", "paragliding", "lakeside relaxation", "photography", "temple visits"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 2, "popularity_score": 96, "altitude": 742, "permits_required": False, "image_url": ""},

    {"name": "Shivapuri Nagarjun National Park", "location": "Kathmandu", "latitude": 27.7833, "longitude": 85.3833, "category": "Nature", "description": "Forest reserve on northern rim of Kathmandu Valley. Day hiking destination with multiple trails through oak and rhododendron forests. Watershed area providing drinking water to Kathmandu. Rich birdlife with over 300 species. Buddhist and Hindu religious sites including Nagi Gompa and Baghdwar spring source of Bagmati River.", "activities": json.dumps(["hiking", "bird watching", "monastery visits", "nature walks", "mountain views"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 75, "altitude": 2563, "permits_required": True, "image_url": ""},

    # Adventure Destinations (15)
    {"name": "Pokhara Paragliding", "location": "Pokhara", "latitude": 28.2096, "longitude": 83.9856, "category": "Adventure", "description": "World-class paragliding destination with stunning mountain views. Fly like a bird over Phewa Lake with Annapurna range as backdrop. Launch from Sarangkot hill at 1,592m. Thermals provide excellent flying conditions. Tandem flights available for beginners with experienced pilots. Unforgettable bird's-eye view of Pokhara valley and surrounding peaks.", "activities": json.dumps(["paragliding", "mountain views", "aerial photography", "adventure sports", "thrill seeking"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 40, "duration_days": 1, "popularity_score": 92, "altitude": 1592, "permits_required": False, "image_url": ""},

    {"name": "Bhotekoshi Bungee Jump", "location": "Sindhupalchowk", "latitude": 27.9667, "longitude": 85.9167, "category": "Adventure", "description": "Nepal's first and highest bungee jump at 160 meters. Jump over Bhote Koshi River gorge on the Tibet border highway. Operated by professional New Zealand company with strict safety standards. Canyon swing also available for different thrill. Spectacular mountain scenery surrounds the jump site. All safety equipment imported and regularly inspected.", "activities": json.dumps(["bungee jumping", "canyon swing", "extreme sports", "adrenaline rush", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 120, "duration_days": 1, "popularity_score": 85, "altitude": 1200, "permits_required": False, "image_url": ""},

    {"name": "White Water Rafting - Trishuli River", "location": "Nuwakot District", "latitude": 27.9167, "longitude": 85.1333, "category": "Adventure", "description": "Popular rafting river between Kathmandu and Pokhara. Class 3-4 rapids suitable for beginners and experienced rafters. Beautiful scenery with terraced hillsides and rural villages. Multiple put-in and take-out points allow flexible trip lengths. Combine with cultural village visits or jungle safari in Chitwan. Best rapids during monsoon season.", "activities": json.dumps(["white water rafting", "river camping", "swimming", "village visits", "adventure"]), "difficulty_level": 2, "best_season": "Monsoon, Autumn", "avg_cost_per_day": 45, "duration_days": 2, "popularity_score": 88, "altitude": 300, "permits_required": False, "image_url": ""},

    # Mountain Biking (5)
    {"name": "Kathmandu Valley Rim Trail", "location": "Kathmandu Valley", "latitude": 27.7172, "longitude": 85.3240, "category": "Adventure", "description": "Multi-day mountain bike circuit around Kathmandu Valley rim. Pass through traditional villages, forests, and agricultural land. Stunning valley and mountain views from multiple viewpoints. Mix of paved roads, dirt tracks, and single trails. Visit ancient temples and monasteries along the way. Total distance approximately 120 km with accommodation in villages.", "activities": json.dumps(["mountain biking", "village tours", "temple visits", "camping", "nature"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 35, "duration_days": 4, "popularity_score": 76, "altitude": 2400, "permits_required": False, "image_url": ""},

    # Additional gems across categories (continuing to reach 100+)
    {"name": "Bandipur", "location": "Tanahun District", "latitude": 27.9319, "longitude": 84.4239, "category": "Cultural", "description": "Preserved hilltop Newari town between Kathmandu and Pokhara. Traditional architecture with paved streets and 18th-century buildings. No vehicles allowed in old bazaar area. Stunning Himalayan views from Tundikhel viewpoint. Local homestays offer authentic cultural immersion. Cave exploration and village walks available. Less touristy alternative to Bandipur.", "activities": json.dumps(["cultural walks", "homestays", "mountain views", "cave visits", "traditional architecture"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 2, "popularity_score": 82, "altitude": 1030, "permits_required": False, "image_url": ""},

    {"name": "Ghorepani Trek", "location": "Myagdi District", "latitude": 28.3942, "longitude": 83.7050, "category": "Trekking", "description": "Classic short trek in Annapurna region with spectacular mountain views. Walk through beautiful rhododendron forests, especially stunning in spring. Traditional Gurung and Magar villages with hospitality. Pre-dawn hike to Poon Hill for sunrise panorama. Suitable for families and beginners. Well-developed trail with good lodges.", "activities": json.dumps(["trekking", "sunrise viewing", "cultural villages", "rhododendrons", "photography"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 40, "duration_days": 4, "popularity_score": 90, "altitude": 2850, "permits_required": True, "image_url": ""},

    {"name": "Bardiya National Park", "location": "Bardiya District", "latitude": 28.3500, "longitude": 81.5167, "category": "Wildlife", "description": "Less crowded alternative to Chitwan with better tiger sighting chances. Largest protected area in Terai lowlands. Home to Bengal tigers, wild elephants, one-horned rhinos, and Gangetic dolphins in Karnali River. Walk safaris, jeep tours, and river rafting available. Tharu cultural experiences in buffer zone villages. More wilderness feel than Chitwan.", "activities": json.dumps(["tiger safari", "river rafting", "walk safaris", "bird watching", "cultural programs"]), "difficulty_level": 1, "best_season": "Winter, Spring", "avg_cost_per_day": 55, "duration_days": 3, "popularity_score": 83, "altitude": 200, "permits_required": True, "image_url": ""},

    {"name": "Ilam Tea Gardens", "location": "Ilam District", "latitude": 26.9089, "longitude": 87.9289, "category": "Nature", "description": "Picturesque tea plantations in far eastern Nepal. Rolling hills covered with neat rows of tea bushes. Fresh mountain air and peaceful rural atmosphere. Visit tea processing factories and taste fresh orthodox tea. Beautiful sunrise views over Kanchenjunga. Pleasant climate year-round. Explore nearby waterfalls and forests.", "activities": json.dumps(["tea garden tours", "tea tasting", "photography", "nature walks", "mountain views"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 2, "popularity_score": 78, "altitude": 1210, "permits_required": False, "image_url": ""},

    {"name": "Gosaikunda Lake", "location": "Rasuwa District", "latitude": 28.0833, "longitude": 85.4167, "category": "Religious", "description": "Sacred alpine lake at 4,380m in Langtang National Park. Important Hindu pilgrimage site dedicated to Lord Shiva. Thousands of pilgrims visit during Janai Purnima festival in August. Trek through rhododendron forests and high alpine terrain. Chain of 108 small lakes surrounding main Gosaikunda. Stunning mountain views and spiritual atmosphere.", "activities": json.dumps(["trekking", "pilgrimage", "mountain lakes", "photography", "religious ceremonies"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 5, "popularity_score": 85, "altitude": 4380, "permits_required": True, "image_url": ""},

    {"name": "Janakpur", "location": "Janakpur", "latitude": 26.7271, "longitude": 85.9245, "category": "Religious", "description": "Ancient city and birthplace of Goddess Sita, consort of Lord Rama. Janaki Mandir is one of the largest temples in Nepal with stunning architecture. Important pilgrimage site for Hindus celebrating Ram-Sita marriage. Unique Maithili culture with distinct art and traditions. Over 100 sacred ponds scattered throughout the city. Vivid paintings depicting Ramayana stories.", "activities": json.dumps(["temple visits", "pilgrimage", "cultural tours", "pond visits", "festivals"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 2, "popularity_score": 88, "altitude": 90, "permits_required": False, "image_url": ""},

    {"name": "Gorkha Durbar", "location": "Gorkha District", "latitude": 28.0000, "longitude": 84.6333, "category": "Cultural", "description": "Historic palace and birthplace of Prithvi Narayan Shah who unified Nepal. Perched on hilltop overlooking Gorkha town. Stunning architecture blending Hindu and Buddhist elements. Important historical site for Nepali national identity. Museum displays weapons and artifacts from Shah dynasty. Panoramic views of Manaslu, Ganesh Himal, and surrounding valleys.", "activities": json.dumps(["historical tours", "palace visits", "museum", "mountain views", "cultural heritage"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 80, "altitude": 1135, "permits_required": False, "image_url": ""},

    {"name": "Begnas Lake", "location": "Kaski District", "latitude": 28.1833, "longitude": 84.0833, "category": "Nature", "description": "Peaceful freshwater lake near Pokhara, less touristy than Phewa. Crystal clear water surrounded by forested hills. Excellent spot for swimming, kayaking, and boating. Lakeside resorts offer quiet retreats. Bird watching and fishing popular activities. Mountain reflections on calm mornings. Connected to Rupa Lake by wetland corridor.", "activities": json.dumps(["boating", "swimming", "kayaking", "bird watching", "relaxation"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 2, "popularity_score": 76, "altitude": 650, "permits_required": False, "image_url": ""},

    {"name": "Dhorpatan Hunting Reserve", "location": "Baglung District", "latitude": 28.5333, "longitude": 83.1000, "category": "Wildlife", "description": "Only hunting reserve in Nepal at high altitude. Home to blue sheep, Himalayan tahr, black bear, and pheasants. Vast alpine meadows and grasslands. Controlled hunting permits issued for specific species. Also suitable for trekking and wildlife photography. Remote location with pristine nature. Traditional Magar villages in buffer zone.", "activities": json.dumps(["wildlife viewing", "trekking", "photography", "cultural tours", "nature"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 40, "duration_days": 4, "popularity_score": 65, "altitude": 3000, "permits_required": True, "image_url": ""},

    {"name": "Khaptad National Park", "location": "Doti District", "latitude": 29.5000, "longitude": 81.1667, "category": "Nature", "description": "Far western national park with unique high-altitude ecosystem. Rolling grasslands dotted with alpine flowers in summer. Named after Khaptad Baba, a revered Hindu sage who meditated here. Religious and natural significance combined. Home to wildlife including Himalayan black bear, leopard, and various birds. Several small lakes and springs add beauty.", "activities": json.dumps(["trekking", "pilgrimage", "wildlife viewing", "meditation", "nature walks"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 35, "duration_days": 3, "popularity_score": 68, "altitude": 3050, "permits_required": True, "image_url": ""},

    {"name": "Shey Phoksundo Lake", "location": "Dolpa District", "latitude": 29.2333, "longitude": 82.9167, "category": "Nature", "description": "Deepest lake in Nepal at 3,611 meters in remote Dolpa region. Stunning turquoise water surrounded by barren cliffs. Featured in the film 'Caravan'. Part of Shey Phoksundo National Park. Tibetan Buddhist culture dominates the area. Ancient Bon Po monastery on lake shore. Very remote requiring multi-day trek or helicopter access.", "activities": json.dumps(["trekking", "photography", "monastery visits", "tibetan culture", "remote adventure"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 60, "duration_days": 10, "popularity_score": 79, "altitude": 3611, "permits_required": True, "image_url": ""},

    {"name": "Tilicho Lake", "location": "Manang District", "latitude": 28.6917, "longitude": 83.8583, "category": "Nature", "description": "One of the highest lakes in the world at 4,919 meters. Side trek from Annapurna Circuit with challenging terrain. Stunning turquoise water surrounded by massive mountain walls. Sacred to Hindus with mythology connecting to Ramayana. Desolate beauty with dramatic landscapes. Weather can change rapidly. Requires good acclimatization and fitness.", "activities": json.dumps(["high altitude trekking", "photography", "adventure", "mountain views", "pilgrimage"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 50, "duration_days": 4, "popularity_score": 84, "altitude": 4919, "permits_required": True, "image_url": ""},

    {"name": "Helambu Trek", "location": "Sindhupalchok", "latitude": 28.1000, "longitude": 85.5333, "category": "Trekking", "description": "Gentle trek north of Kathmandu through Hyolmo villages. Lower altitude trek ideal for beginners. Beautiful forests, terraced fields, and mountain views. Experience unique Hyolmo Sherpa culture and Buddhist monasteries. Less crowded than popular treks. Can be combined with Langtang trek. Good rhododendron blooms in spring.", "activities": json.dumps(["trekking", "cultural immersion", "monastery visits", "village stays", "nature"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 7, "popularity_score": 74, "altitude": 3640, "permits_required": True, "image_url": ""},

    {"name": "Mardi Himal Trek", "location": "Kaski District", "latitude": 28.3167, "longitude": 83.9500, "category": "Trekking", "description": "Recently opened trek in Annapurna region with stunning close-up mountain views. Less crowded alternative to classic routes. Trek through rhododendron and bamboo forests to high camp. Amazing views of Machhapuchhre (Fishtail) and Mardi Himal. Ridge walking with 360-degree Himalayan panoramas. Teahouse accommodation available but basic.", "activities": json.dumps(["trekking", "mountain photography", "ridge walking", "nature", "solitude"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 5, "popularity_score": 86, "altitude": 4500, "permits_required": True, "image_url": ""},

    {"name": "Pikey Peak Trek", "location": "Solukhumbu District", "latitude": 27.6167, "longitude": 86.5833, "category": "Trekking", "description": "Lower Everest region trek with panoramic mountain views. Sir Edmund Hillary's favorite viewpoint for Everest panorama. See eight of world's fourteen 8000m peaks from summit. Off-the-beaten-path trek through Sherpa villages. Buddhist monasteries and prayer flags. Cheaper alternative to classic Everest treks. Beautiful sunrise views from Pikey Peak.", "activities": json.dumps(["trekking", "sunrise viewing", "sherpa culture", "monastery visits", "photography"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 40, "duration_days": 6, "popularity_score": 77, "altitude": 4065, "permits_required": True, "image_url": ""},

    {"name": "Panch Pokhari Trek", "location": "Sindhupalchok", "latitude": 28.0500, "longitude": 85.7500, "category": "Trekking", "description": "Remote trek to five sacred lakes at 4,100 meters. Important Hindu and Buddhist pilgrimage site. Festival in August attracts thousands of pilgrims. Trek through rhododendron forests with mountain views. Less developed trail with basic facilities. Wildlife including red panda possible. Stunning sunrise over lakes and mountains.", "activities": json.dumps(["trekking", "pilgrimage", "alpine lakes", "wildlife spotting", "photography"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 40, "duration_days": 8, "popularity_score": 72, "altitude": 4100, "permits_required": True, "image_url": ""},

    {"name": "Khopra Ridge Trek", "location": "Kaski/Myagdi District", "latitude": 28.3667, "longitude": 83.6000, "category": "Trekking", "description": "Community-managed trek in Annapurna region. Alternative route with spectacular mountain views. Visit Khayer Lake, sacred to Hindus and Buddhists. Ridge walking with close views of Dhaulagiri and Annapurna South. Community lodges run by local villagers. More peaceful than main Annapurna routes. Can be combined with Poon Hill trek.", "activities": json.dumps(["trekking", "community tourism", "sacred lake visit", "mountain views", "cultural exchange"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 8, "popularity_score": 79, "altitude": 3660, "permits_required": True, "image_url": ""},

    {"name": "Nagarkot", "location": "Bhaktapur District", "latitude": 27.7172, "longitude": 85.5206, "category": "Nature", "description": "Hill station near Kathmandu famous for sunrise views. Panoramic Himalayan views from Annapurna to Everest on clear days. Popular weekend getaway from Kathmandu. Numerous hotels and resorts. Mountain biking and hiking trails. Watch sunrise over Himalayas with Kathmandu Valley below. Easy access makes it perfect for short trips.", "activities": json.dumps(["sunrise viewing", "hiking", "mountain biking", "photography", "relaxation"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 35, "duration_days": 2, "popularity_score": 89, "altitude": 2175, "permits_required": False, "image_url": ""},

    {"name": "Dhulikhel", "location": "Kavrepalanchok", "latitude": 27.6167, "longitude": 85.5500, "category": "Nature", "description": "Ancient Newari town on old trade route to Tibet. Stunning Himalayan views from multiple viewpoints. Traditional architecture and temples. Starting point for various hiking trails. Namobuddha monastery nearby is important Buddhist site. Resort hotels with mountain views. Traditional pottery and weaving crafts. Peaceful alternative to Kathmandu.", "activities": json.dumps(["mountain views", "cultural walks", "monastery visits", "hiking", "traditional crafts"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 2, "popularity_score": 81, "altitude": 1550, "permits_required": False, "image_url": ""},

    {"name": "Namobuddha", "location": "Kavrepalanchok", "latitude": 27.5833, "longitude": 85.5833, "category": "Religious", "description": "One of three most important Buddhist pilgrimage sites in Nepal. Legend says Buddha offered his body to starving tigress here. Beautiful monastery with monks practicing traditional Buddhism. Peaceful hilltop location with mountain views. Short hike from Dhulikhel through villages. Prayer flags, stupas, and meditation areas. Annual festivals attract thousands of pilgrims.", "activities": json.dumps(["pilgrimage", "monastery visits", "meditation", "hiking", "buddhist culture"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 1, "popularity_score": 82, "altitude": 1750, "permits_required": False, "image_url": ""},

    {"name": "Sarangkot", "location": "Kaski District", "latitude": 28.2442, "longitude": 83.9525, "category": "Nature", "description": "Hill station above Pokhara with spectacular Annapurna views. Popular sunrise viewpoint with close-up views of Machhapuchhre. Paragliding launch site with multiple operators. Short hike or drive from Pokhara. See Annapurna range turning golden at sunrise. Peaceful village setting with guesthouses. Mountain biking trails down to Pokhara.", "activities": json.dumps(["sunrise viewing", "paragliding", "mountain views", "hiking", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 1, "popularity_score": 90, "altitude": 1600, "permits_required": False, "image_url": ""},

    {"name": "Koshi Tappu Wildlife Reserve", "location": "Sunsari/Saptari", "latitude": 26.6500, "longitude": 87.0333, "category": "Wildlife", "description": "Important wetland reserve in eastern Terai. Over 500 bird species make it paradise for birdwatchers. Last refuge of wild water buffalo (arna). Gangetic dolphins in Koshi River. Migratory birds winter here from Siberia and Tibet. Boat safaris and bird watching towers. Less crowded than Chitwan. Unique riverine and wetland ecosystem.", "activities": json.dumps(["bird watching", "boat safaris", "wildlife viewing", "photography", "nature walks"]), "difficulty_level": 1, "best_season": "Winter", "avg_cost_per_day": 45, "duration_days": 2, "popularity_score": 73, "altitude": 75, "permits_required": True, "image_url": ""},

    {"name": "Parsa National Park", "location": "Parsa District", "latitude": 27.4000, "longitude": 84.9000, "category": "Wildlife", "description": "Recently upgraded from wildlife reserve to national park. Contiguous with Chitwan forming large protected area. Sal forests, grasslands, and wetlands. Bengal tigers, sloth bears, elephants, and gaur. Less touristy than Chitwan with wilderness feel. Includes Someshwor Hills in north. Important wildlife corridor between Nepal and India.", "activities": json.dumps(["wildlife safari", "jungle walks", "bird watching", "photography", "nature"]), "difficulty_level": 1, "best_season": "Winter, Spring", "avg_cost_per_day": 50, "duration_days": 2, "popularity_score": 70, "altitude": 150, "permits_required": True, "image_url": ""},

    {"name": "Annapurna Base Camp Trek", "location": "Kaski District", "latitude": 28.5311, "longitude": 83.8742, "category": "Trekking", "description": "Trek into the heart of Annapurna sanctuary surrounded by towering peaks. Amphitheater of mountains including Annapurna I (8091m), Machhapuchhre, and Hiunchuli. Pass through diverse landscapes from subtropical to alpine. Hot springs at Jhinu Danda. Teahouse trek with good facilities. Spectacular sunrise views from base camp. Moderate difficulty suitable for most fitness levels.", "activities": json.dumps(["trekking", "mountain views", "hot springs", "photography", "cultural villages"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 50, "duration_days": 10, "popularity_score": 95, "altitude": 4130, "permits_required": True, "image_url": ""},

    {"name": "Nar Phu Valley Trek", "location": "Manang District", "latitude": 28.7167, "longitude": 84.3167, "category": "Trekking", "description": "Remote restricted area trek in Annapurna region. Ancient Tibetan villages with preserved culture. Dramatic gorges, cliffs, and unique rock formations. Restricted area requiring special permits and guide. Visit Tashi Lhakhang monastery. Can be combined with Annapurna Circuit. Very few tourists maintain authentic atmosphere.", "activities": json.dumps(["trekking", "tibetan culture", "ancient monasteries", "remote villages", "photography"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 70, "duration_days": 14, "popularity_score": 77, "altitude": 5320, "permits_required": True, "image_url": ""},

    {"name": "Rara National Park Trek", "location": "Mugu/Jumla", "latitude": 29.5264, "longitude": 82.0809, "category": "Trekking", "description": "Trek to Nepal's largest lake in remote northwestern region. Pristine wilderness with minimal tourism impact. Pine, spruce, and juniper forests around lake. Abundant wildlife including Himalayan black bear and red panda. Best done as camping trek or by flight to Talcha Airport. Crystal clear blue lake surrounded by snow peaks.", "activities": json.dumps(["trekking", "camping", "wildlife viewing", "photography", "solitude"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 60, "duration_days": 10, "popularity_score": 75, "altitude": 2990, "permits_required": True, "image_url": ""},

    {"name": "Three Passes Trek", "location": "Solukhumbu District", "latitude": 27.9647, "longitude": 86.7833, "category": "Trekking", "description": "Ultimate Everest region challenge crossing three high passes. Kongma La, Cho La, and Renjo La all above 5000m. Complete circuit including Everest Base Camp and Gokyo Lakes. Extended trek with supreme mountain views. Requires excellent fitness and acclimatization. Visit four valleys with different perspectives. Most comprehensive Everest region experience.", "activities": json.dumps(["extreme trekking", "high passes", "mountain lakes", "glacier views", "photography"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 65, "duration_days": 20, "popularity_score": 81, "altitude": 5535, "permits_required": True, "image_url": ""},

    {"name": "Tamang Heritage Trail", "location": "Rasuwa District", "latitude": 28.1833, "longitude": 85.3500, "category": "Trekking", "description": "Cultural trek through traditional Tamang villages. Experience authentic Tamang culture, food, and homestays. Visit ancient monasteries and hot springs. Lower altitude trek suitable for families. Combine with Langtang trek. Community-based tourism supporting local villages. Beautiful mountain views without extreme altitude.", "activities": json.dumps(["cultural trekking", "homestays", "hot springs", "monastery visits", "tamang culture"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 40, "duration_days": 7, "popularity_score": 79, "altitude": 3700, "permits_required": True, "image_url": ""},

    {"name": "Rolwaling Valley Trek", "location": "Dolakha District", "latitude": 27.8500, "longitude": 86.2500, "category": "Trekking", "description": "Remote valley trek between Kathmandu and Everest regions. Cross Tashi Lapcha Pass connecting to Khumbu. Sacred valley with Tsho Rolpa glacial lake. Very remote with minimal facilities requiring camping. Sherpa villages and Buddhist culture. Technical pass crossing requiring mountaineering skills. Stunning mountain scenery and isolation.", "activities": json.dumps(["extreme trekking", "mountaineering", "glacier crossing", "remote culture", "wilderness"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 75, "duration_days": 18, "popularity_score": 68, "altitude": 5755, "permits_required": True, "image_url": ""},

    {"name": "Mohare Danda Trek", "location": "Myagdi/Parbat District", "latitude": 28.3833, "longitude": 83.6833, "category": "Trekking", "description": "Newly developed community eco-trek in Annapurna region. Spectacular 360-degree mountain panoramas from Mohare Danda. Community lodges owned and operated by local villages. Less crowded alternative to Poon Hill. Rhododendron forests and terraced farmlands. Authentic rural cultural experience. Supports sustainable tourism development.", "activities": json.dumps(["eco-trekking", "community tourism", "mountain views", "cultural immersion", "sustainable travel"]), "difficulty_level": 2, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 5, "popularity_score": 76, "altitude": 3300, "permits_required": True, "image_url": ""},

    {"name": "Kakani", "location": "Nuwakot District", "latitude": 27.8000, "longitude": 85.2500, "category": "Nature", "description": "Hill station northwest of Kathmandu with panoramic mountain views. Popular weekend destination for locals. Strawberry farming and flower nurseries. Mountain biking and hiking trails. Memorial park dedicated to Thai Airways crash victims. Quiet retreat from Kathmandu's chaos. Clear day views from Annapurna to Everest.", "activities": json.dumps(["hiking", "mountain views", "strawberry picking", "photography", "mountain biking"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 1, "popularity_score": 71, "altitude": 2073, "permits_required": False, "image_url": ""},

    {"name": "Khokana and Bungamati", "location": "Lalitpur District", "latitude": 27.6333, "longitude": 85.2833, "category": "Cultural", "description": "Traditional Newari villages preserving ancient lifestyle. Famous for mustard oil production using traditional methods. Beautiful brick-paved streets and traditional architecture. Karya Binayak Temple and Rato Machhindranath Temple. Short distance from Kathmandu but feels like stepping back in time. Agricultural terraces and traditional farming. UNESCO World Heritage Site candidacy.", "activities": json.dumps(["cultural walks", "traditional villages", "temple visits", "photography", "rural life"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 74, "altitude": 1350, "permits_required": False, "image_url": ""},

    {"name": "Dakshinkali Temple", "location": "Kathmandu District", "latitude": 27.6167, "longitude": 85.2833, "category": "Religious", "description": "Important Hindu temple dedicated to Goddess Kali. Animal sacrifices performed especially on Tuesdays and Saturdays. Located in gorge where two streams meet. Popular pilgrimage site for locals. Colorful religious ceremonies and offerings. Surrounded by forested hills. Pharping and Chovar nearby for extended visit.", "activities": json.dumps(["temple visits", "religious ceremonies", "cultural observation", "pilgrimage", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 15, "duration_days": 1, "popularity_score": 80, "altitude": 1350, "permits_required": False, "image_url": ""},

    {"name": "Manakamana Temple", "location": "Gorkha District", "latitude": 27.9833, "longitude": 84.5667, "category": "Religious", "description": "Hindu temple dedicated to wish-fulfilling goddess. Reached by cable car ride with valley views. Important pilgrimage site especially for newlyweds. Animal sacrifices performed by devotees. Cable car makes visit easy and scenic. Panoramic views of Trishuli and Marsyangdi rivers. Combine with visit to Gorkha Durbar.", "activities": json.dumps(["cable car ride", "temple visits", "pilgrimage", "valley views", "religious ceremonies"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 1, "popularity_score": 87, "altitude": 1302, "permits_required": False, "image_url": ""},

    {"name": "Budhanilkantha Temple", "location": "Kathmandu", "latitude": 27.7667, "longitude": 85.3667, "category": "Religious", "description": "Temple featuring large reclining Vishnu statue in water pond. 5-meter stone carving from 7th century. Important pilgrimage site for Hindus. Beautiful peaceful setting at base of Shivapuri hill. Morning rituals particularly atmospheric. Legend says carving floated downstream and settled here. Reigning monarch cannot visit due to legend.", "activities": json.dumps(["temple visits", "religious ceremonies", "photography", "cultural heritage", "pilgrimage"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 15, "duration_days": 1, "popularity_score": 83, "altitude": 1398, "permits_required": False, "image_url": ""},

    {"name": "Pharping", "location": "Kathmandu District", "latitude": 27.5833, "longitude": 85.3000, "category": "Religious", "description": "Important Buddhist and Hindu pilgrimage site. Cave where Guru Rinpoche attained enlightenment. Multiple monasteries and meditation centers. Sacred to both Hindus and Buddhists. Peaceful spiritual atmosphere. Dakshinkali Temple nearby. Growing meditation tourism destination. Numerous retreat centers.", "activities": json.dumps(["monastery visits", "meditation", "cave visits", "pilgrimage", "spiritual retreat"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 2, "popularity_score": 77, "altitude": 1524, "permits_required": False, "image_url": ""},

    {"name": "Kopan Monastery", "location": "Kathmandu", "latitude": 27.7333, "longitude": 85.3667, "category": "Religious", "description": "Tibetan Buddhist monastery offering meditation courses. Popular destination for Western Buddhist students. Regular teachings and retreats. Peaceful hilltop location overlooking Boudhanath. Bookshop with extensive Buddhist literature. Vegetarian meals and simple accommodation. Beautiful monastery architecture and gardens.", "activities": json.dumps(["meditation courses", "buddhist teachings", "monastery stays", "spiritual learning", "retreats"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 30, "duration_days": 3, "popularity_score": 81, "altitude": 1400, "permits_required": False, "image_url": ""},

    {"name": "White Water Rafting - Seti River", "location": "Kaski/Tanahun", "latitude": 28.0833, "longitude": 84.2500, "category": "Adventure", "description": "Gentle rafting river perfect for families and beginners. Class 2-3 rapids with warm water. Beautiful scenery through rural countryside. Short distance from Pokhara. Multi-day trips available with riverside camping. Swimming and cliff jumping opportunities. Combine with Chitwan visit. Good introduction to rafting.", "activities": json.dumps(["rafting", "swimming", "camping", "family adventure", "nature"]), "difficulty_level": 1, "best_season": "Monsoon, Autumn", "avg_cost_per_day": 40, "duration_days": 2, "popularity_score": 82, "altitude": 250, "permits_required": False, "image_url": ""},

    {"name": "White Water Rafting - Kali Gandaki", "location": "Syangja District", "latitude": 28.0667, "longitude": 83.6667, "category": "Adventure", "description": "Exciting rafting through world's deepest gorge. Class 3-4 rapids with big volume water. Multi-day expedition with wilderness camping. Spectacular scenery between Dhaulagiri and Annapurna. Technical rapids require experienced rafters. Hot springs along the way. Remote sections with limited access.", "activities": json.dumps(["extreme rafting", "camping", "gorge scenery", "hot springs", "adventure"]), "difficulty_level": 4, "best_season": "Monsoon, Autumn", "avg_cost_per_day": 55, "duration_days": 3, "popularity_score": 78, "altitude": 300, "permits_required": False, "image_url": ""},

    {"name": "White Water Rafting - Sun Koshi", "location": "Multi-District", "latitude": 27.6500, "longitude": 85.9000, "category": "Adventure", "description": "Classic multi-day rafting expedition, River of Gold. 270km journey through remote gorges and valleys. Class 3-4+ rapids with pristine beaches for camping. One of top ten river trips in the world. Experience rural Nepal from river perspective. 7-9 day expedition. Ends near Chitwan for jungle safari combination.", "activities": json.dumps(["expedition rafting", "beach camping", "wilderness", "village encounters", "adventure"]), "difficulty_level": 3, "best_season": "Monsoon, Autumn", "avg_cost_per_day": 50, "duration_days": 8, "popularity_score": 84, "altitude": 200, "permits_required": False, "image_url": ""},

    {"name": "Canyoning in Pokhara", "location": "Kaski District", "latitude": 28.2096, "longitude": 83.9856, "category": "Adventure", "description": "Waterfall canyoning adventure near Pokhara. Abseil down waterfalls, jump into pools, and slide down natural chutes. Multiple canyon options for different skill levels. Professional guides and safety equipment provided. Half-day or full-day adventures. Beautiful natural setting. Adrenaline rush combined with nature.", "activities": json.dumps(["canyoning", "waterfall rappelling", "cliff jumping", "swimming", "adventure sports"]), "difficulty_level": 2, "best_season": "Spring, Summer, Autumn", "avg_cost_per_day": 60, "duration_days": 1, "popularity_score": 86, "altitude": 800, "permits_required": False, "image_url": ""},

    {"name": "Zipline Pokhara", "location": "Kaski District", "latitude": 28.2500, "longitude": 83.9667, "category": "Adventure", "description": "One of world's longest and steepest ziplines. 1.8km ride from Sarangkot to Hemja. Reach speeds up to 120 km/h at 600m elevation. Spectacular views of Annapurna range and Pokhara valley. Safe and professionally operated. Combine with paragliding for adventure day. Superman-style flying position option.", "activities": json.dumps(["ziplining", "extreme sports", "mountain views", "adrenaline", "adventure"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 80, "duration_days": 1, "popularity_score": 89, "altitude": 1592, "permits_required": False, "image_url": ""},

    {"name": "Rock Climbing - Nagarjun", "location": "Kathmandu", "latitude": 27.7500, "longitude": 85.2833, "category": "Adventure", "description": "Sport climbing area on Nagarjun hill near Kathmandu. Multiple bolted routes from beginner to advanced. Limestone cliffs with good holds. Close to city for afternoon climbing sessions. Growing climbing community and culture. Equipment rental available. Beautiful forest setting. Good for training before Himalayan peaks.", "activities": json.dumps(["rock climbing", "sport climbing", "training", "outdoor adventure", "nature"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 25, "duration_days": 1, "popularity_score": 72, "altitude": 1600, "permits_required": False, "image_url": ""},

    {"name": "Mountain Biking - Upper Mustang", "location": "Mustang District", "latitude": 28.9953, "longitude": 83.8821, "category": "Adventure", "description": "Epic mountain biking adventure through forbidden kingdom. Desert landscapes and Tibetan culture. Challenging terrain with high passes. Support vehicle for luggage. Ancient caves and monasteries. Restricted area requiring permits. Unique biking experience in Himalayan rain shadow.", "activities": json.dumps(["mountain biking", "cultural exploration", "high altitude", "desert landscape", "adventure"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 90, "duration_days": 10, "popularity_score": 79, "altitude": 3840, "permits_required": True, "image_url": ""},

    {"name": "Mountain Biking - Annapurna Circuit", "location": "Annapurna Region", "latitude": 28.5965, "longitude": 83.8820, "category": "Adventure", "description": "Challenging bike ride around Annapurna massif. Cross Thorong La Pass at 5,416m pushing bikes. Diverse terrain from jungle roads to high desert. Support team for luggage and difficult sections. Technical descents and long climbs. Teahouse accommodation. Epic adventure for experienced cyclists.", "activities": json.dumps(["mountain biking", "high pass crossing", "endurance cycling", "cultural villages", "adventure"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 65, "duration_days": 14, "popularity_score": 75, "altitude": 5416, "permits_required": True, "image_url": ""},

    {"name": "Kayaking in Phewa Lake", "location": "Pokhara", "latitude": 28.2096, "longitude": 83.9856, "category": "Adventure", "description": "Peaceful kayaking on Nepal's second largest lake. Rent kayaks hourly or daily. Paddle to Tal Barahi Temple island. Mountain reflections in calm morning water. Suitable for beginners and families. Combine with Pokhara sightseeing. Sunset kayaking particularly beautiful. Safe and relaxing water activity.", "activities": json.dumps(["kayaking", "lake paddling", "temple visits", "photography", "water sports"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 20, "duration_days": 1, "popularity_score": 84, "altitude": 742, "permits_required": False, "image_url": ""},

    {"name": "Ultra-light Aircraft Flight", "location": "Pokhara", "latitude": 28.2096, "longitude": 83.9856, "category": "Adventure", "description": "Scenic flights in ultra-light aircraft over Pokhara. Close-up aerial views of Annapurna range. Different flight durations available. Fly along mountain ridges and valleys. Safer alternative to helicopter with open cockpit experience. Professional pilots with perfect safety record. Unique perspective of Himalayas.", "activities": json.dumps(["scenic flights", "aerial views", "mountain flying", "adventure", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 150, "duration_days": 1, "popularity_score": 87, "altitude": 742, "permits_required": False, "image_url": ""},

    {"name": "Everest Base Camp Helicopter Tour", "location": "Solukhumbu District", "latitude": 27.9881, "longitude": 86.9250, "category": "Adventure", "description": "Helicopter flight to Everest Base Camp for those unable to trek. Land at Kala Patthar viewpoint for close Everest views. Breakfast at Everest View Hotel. Fly over Khumbu glacier and icefall. 4-5 hour return trip from Kathmandu. Altitude acclimatization not required. Expensive but unforgettable experience.", "activities": json.dumps(["helicopter tour", "everest views", "aerial sightseeing", "luxury adventure", "photography"]), "difficulty_level": 1, "best_season": "Spring, Autumn", "avg_cost_per_day": 1200, "duration_days": 1, "popularity_score": 90, "altitude": 5364, "permits_required": True, "image_url": ""},

    {"name": "Langtang Helicopter Tour", "location": "Rasuwa District", "latitude": 28.2096, "longitude": 85.5450, "category": "Adventure", "description": "Helicopter tour to Langtang Valley and Kyanjin Gompa. See earthquake-affected areas from above. Land at Kyanjin for breakfast with mountain views. Fly over Langtang Glacier. More affordable than Everest helicopter tour. Beautiful valley scenery. Half-day trip from Kathmandu.", "activities": json.dumps(["helicopter tour", "mountain views", "aerial sightseeing", "valley exploration", "photography"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 600, "duration_days": 1, "popularity_score": 81, "altitude": 3870, "permits_required": True, "image_url": ""},

    {"name": "Skiing in Nepal", "location": "Kalapatthar", "latitude": 27.9958, "longitude": 86.8289, "category": "Adventure", "description": "Heli-skiing adventure in Khumbu region. Untouched powder snow runs. For expert skiers only. Helicopter access to remote slopes. Guide and safety equipment essential. Very expensive expedition-style skiing. Extremely limited season and weather dependent. Ultimate Himalayan skiing experience.", "activities": json.dumps(["heli-skiing", "extreme sports", "powder skiing", "mountaineering", "adventure"]), "difficulty_level": 5, "best_season": "Winter", "avg_cost_per_day": 2000, "duration_days": 7, "popularity_score": 60, "altitude": 5545, "permits_required": True, "image_url": ""},

    {"name": "Motorcycle Tours - Kathmandu to Pokhara", "location": "Multi-District", "latitude": 27.7172, "longitude": 85.3240, "category": "Adventure", "description": "Scenic motorcycle journey on Prithvi Highway. Ride through river valleys and hillsides. Stop at viewpoints and local restaurants. Royal Enfield bikes popular choice. Guided or self-guided options. Experience rural Nepal from the road. 6-7 hour ride with stops. Can extend to Annapurna circuit roads.", "activities": json.dumps(["motorcycle touring", "road trip", "scenic riding", "cultural stops", "adventure"]), "difficulty_level": 2, "best_season": "All", "avg_cost_per_day": 50, "duration_days": 2, "popularity_score": 83, "altitude": 200, "permits_required": False, "image_url": ""},

    {"name": "Jungle Safari - Shuklaphanta National Park", "location": "Kanchanpur District", "latitude": 28.8500, "longitude": 80.2500, "category": "Wildlife", "description": "Far western national park with large swamp deer population. Home to Bengal tigers, elephants, and various deer species. Grasslands and sal forests. Less touristy than Chitwan and Bardiya. Good bird watching with over 450 species. Jeep safaris and nature walks. Nearby Mahakali River forms India border.", "activities": json.dumps(["wildlife safari", "bird watching", "jeep tours", "nature walks", "photography"]), "difficulty_level": 1, "best_season": "Winter, Spring", "avg_cost_per_day": 50, "duration_days": 2, "popularity_score": 67, "altitude": 174, "permits_required": True, "image_url": ""},

    {"name": "Jomsom", "location": "Mustang District", "latitude": 28.7805, "longitude": 83.7231, "category": "Nature", "description": "Town in Kali Gandaki gorge between Dhaulagiri and Annapurna. Strong afternoon winds famous for apple brandy production. Starting point for Muktinath pilgrimage. Airport with mountain flights from Pokhara. Tibetan-influenced culture and architecture. Shops selling local apple products. Hub for Upper Mustang treks.", "activities": json.dumps(["sightseeing", "apple products", "tibetan culture", "mountain views", "bazaar shopping"]), "difficulty_level": 1, "best_season": "All", "avg_cost_per_day": 35, "duration_days": 2, "popularity_score": 82, "altitude": 2743, "permits_required": False, "image_url": ""},

    {"name": "Kagbeni", "location": "Mustang District", "latitude": 28.8333, "longitude": 83.7833, "category": "Cultural", "description": "Medieval village at gateway to Upper Mustang. Ancient monastery and narrow alleyways. Traditional mud-brick architecture. Checkpoint for Upper Mustang permits. Kali Gandaki River junction. Starting point for Muktinath pilgrimage. Well-preserved medieval atmosphere. Sunset views spectacular.", "activities": json.dumps(["cultural exploration", "monastery visits", "traditional architecture", "photography", "village walks"]), "difficulty_level": 1, "best_season": "Spring, Autumn", "avg_cost_per_day": 30, "duration_days": 1, "popularity_score": 78, "altitude": 2810, "permits_required": False, "image_url": ""},

    {"name": "Marpha", "location": "Mustang District", "latitude": 28.7500, "longitude": 83.7000, "category": "Cultural", "description": "Picturesque Thakali village on Annapurna Circuit. Famous for apple orchards and brandy production. Clean cobblestone streets and whitewashed houses. Local distilleries welcome visitors. Buddhist monastery and traditional architecture. Best apples in Nepal. Gateway to Muktinath. Charming stopover destination.", "activities": json.dumps(["village walks", "apple tasting", "brandy distillery", "cultural tours", "photography"]), "difficulty_level": 1, "best_season": "Spring, Autumn", "avg_cost_per_day": 30, "duration_days": 1, "popularity_score": 80, "altitude": 2670, "permits_required": False, "image_url": ""},

    {"name": "Namche Bazaar", "location": "Solukhumbu District", "latitude": 27.8017, "longitude": 86.7133, "category": "Cultural", "description": "Sherpa capital and gateway to Everest region. Colorful Saturday market selling trekking supplies and local goods. Acclimatization stop for Everest trekkers. Excellent mountain views of Everest, Lhotse, and Ama Dablam. Museums dedicated to Sherpa culture and climbing history. Bakeries, restaurants, and gear shops. Vibrant mountain town atmosphere.", "activities": json.dumps(["market shopping", "acclimatization", "mountain views", "museum visits", "sherpa culture"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 50, "duration_days": 2, "popularity_score": 93, "altitude": 3440, "permits_required": True, "image_url": ""},

    {"name": "Tengboche Monastery", "location": "Solukhumbu District", "latitude": 27.8358, "longitude": 86.7647, "category": "Religious", "description": "Largest monastery in Khumbu region with spectacular mountain backdrop. Active monastery with monks performing daily prayers. Mani Rimdu festival in autumn attracts pilgrims and tourists. Incredible views of Everest, Nuptse, Lhotse, and Ama Dablam. Major stop on Everest Base Camp trek. Spiritual atmosphere. Destroyed by earthquake and rebuilt.", "activities": json.dumps(["monastery visits", "prayer ceremonies", "mountain views", "festivals", "meditation"]), "difficulty_level": 3, "best_season": "Spring, Autumn", "avg_cost_per_day": 45, "duration_days": 1, "popularity_score": 91, "altitude": 3867, "permits_required": True, "image_url": ""},

    {"name": "Island Peak Climbing", "location": "Solukhumbu District", "latitude": 27.9189, "longitude": 86.9378, "category": "Adventure", "description": "Popular trekking peak for climbers. 6,189m summit with technical climbing sections. Requires basic mountaineering skills and equipment. Combine with Everest Base Camp trek. Glacier travel and fixed ropes. Summit day starts pre-dawn. Stunning 360-degree mountain views from top. Entry-level Himalayan peak.", "activities": json.dumps(["peak climbing", "mountaineering", "glacier walking", "summit push", "extreme adventure"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 100, "duration_days": 18, "popularity_score": 85, "altitude": 6189, "permits_required": True, "image_url": ""},

    {"name": "Mera Peak Climbing", "location": "Solukhumbu District", "latitude": 27.7164, "longitude": 86.8689, "category": "Adventure", "description": "Highest trekking peak in Nepal at 6,476m. Non-technical climb suitable for strong trekkers. Spectacular views of Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga. Remote approach through pristine valleys. Glacier travel requires basic mountaineering skills. Less crowded than Island Peak. Excellent acclimatization climb.", "activities": json.dumps(["peak climbing", "high altitude mountaineering", "glacier travel", "remote trekking", "photography"]), "difficulty_level": 4, "best_season": "Spring, Autumn", "avg_cost_per_day": 110, "duration_days": 20, "popularity_score": 82, "altitude": 6476, "permits_required": True, "image_url": ""},

    {"name": "Lobuche Peak Climbing", "location": "Solukhumbu District", "latitude": 27.9400, "longitude": 86.8089, "category": "Adventure", "description": "Challenging trekking peak near Everest Base Camp. Technical climbing with steep snow and ice slopes. Two summits - East (6,119m) and West (6,145m). Requires good mountaineering skills. Excellent acclimatization from EBC trek. Close-up views of Everest's south face. Popular with aspiring Everest climbers for training.", "activities": json.dumps(["technical climbing", "mountaineering", "ice climbing", "summit push", "training"]), "difficulty_level": 5, "best_season": "Spring, Autumn", "avg_cost_per_day": 120, "duration_days": 18, "popularity_score": 80, "altitude": 6119, "permits_required": True, "image_url": ""},
]

def add_destinations():
    db = SessionLocal()
    try:
        # Check existing count
        existing_count = db.query(Destination).count()
        print(f"Current destinations in database: {existing_count}")

        # Add new destinations
        added = 0
        for dest_data in destinations_data:
            # Check if destination already exists
            existing = db.query(Destination).filter(
                Destination.name == dest_data['name']
            ).first()

            if not existing:
                destination = Destination(**dest_data)
                db.add(destination)
                added += 1

        db.commit()
        print(f"Successfully added {added} new destinations!")

        # Print final count
        final_count = db.query(Destination).count()
        print(f"Total destinations now: {final_count}")

    except Exception as e:
        print(f"Error adding destinations: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    add_destinations()
